hashredis:
  # 是否启用节点初始打印
  # node initial print switch
  enable-print: 0
  # 节点检查时间周期（秒）
  # node check period (second)
  check-period: 5
  # redis server list
  servers:
  - database: 10
    host: 172.20.1.7
    port: 6379
    # password: 123456
  - database: 11
    host: 172.20.1.7
    port: 6379
    # password: 123456
  - database: 12
    host: 172.20.1.7
    port: 6379
    # password: 123456
